name: 'Hexo Action'
description: 'Hexo CI/CD action for automating deployment.'
author: 'sma11black'
inputs:
  user_name:
    description: 'Github user name'
    required: true
    default: ''
  user_email:
    description: 'Github email'
    required: true
    default: ''
  deploy_key:
    description: 'The deploy key for Github Pages repo'
    required: true
    default: ''
outputs:
  notify: # id of output
    description: 'The notification of deployment result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user_name }}
    - ${{ inputs.user_email }}
    - ${{ inputs.deploy_key }}
branding:
  icon: 'package'  
  color: 'blue'